# Generated by Django 4.1.1 on 2022-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='post_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='post text'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='todo',
            field=models.CharField(blank=True, max_length=50, verbose_name='todo'),
        ),
    ]
