# Generated by Django 4.1.1 on 2022-10-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('planner', '0003_alter_planner_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
